from __future__ import annotations

import shlex

from pydantic import SecretStr

from app.deployment.ssh import RemoteCommandExecutor
from app.deployment.types import SshConnectionSpec, ThreeXUiConfig


class ThreeXUiInstaller:
    """Isolated 3X-UI install/config extraction component.

    The implementation follows the current upstream unattended-install contract. Credentials are
    generated by 3X-UI and retrieved from its root-only install result file; they are never included
    in ASO command strings or logs.
    """

    INSTALL_URL = "https://raw.githubusercontent.com/MHSanaei/3x-ui/main/install.sh"
    RESULT_FILE = "/etc/x-ui/install-result.env"

    def __init__(self, executor: RemoteCommandExecutor, *, version: str | None = None) -> None:
        self.executor = executor
        self.version = version

    async def install(self, spec: SshConnectionSpec, *, public_host: str) -> None:
        version_arg = f" {shlex.quote(self.version)}" if self.version else ""
        command = (
            "set -eu; "
            "tmp=/tmp/aso-3xui-install.sh; "
            f"curl -fsSL {shlex.quote(self.INSTALL_URL)} -o \"$tmp\"; "
            "chmod 700 \"$tmp\"; "
            f"XUI_NONINTERACTIVE=1 XUI_SERVER_IP={shlex.quote(public_host)} "
            f"bash \"$tmp\"{version_arg}; "
            "rm -f \"$tmp\""
        )
        result = await self.executor.run(spec, command, timeout_seconds=900.0)
        if result.exit_status != 0:
            raise RuntimeError("3X-UI unattended installation failed")

    async def verify_installation(self, spec: SshConnectionSpec) -> None:
        command = (
            "set -eu; "
            "test -x /usr/bin/x-ui; "
            f"test -r {self.RESULT_FILE}; "
            "(systemctl is-active --quiet x-ui || rc-service x-ui status >/dev/null 2>&1)"
        )
        result = await self.executor.run(spec, command, timeout_seconds=30.0)
        if result.exit_status != 0:
            raise RuntimeError("3X-UI installation verification failed")

    async def read_configuration(self, spec: SshConnectionSpec) -> ThreeXUiConfig:
        # Source the shell-escaped upstream file and emit values separated by NUL. stdout is kept in
        # memory only; the SSH executor intentionally never logs command output.
        command = (
            "set -eu; "
            f". {self.RESULT_FILE}; "
            "printf '%s\\0%s\\0%s\\0%s\\0%s\\0%s\\0%s\\0' "
            '"$XUI_USERNAME" "$XUI_PASSWORD" "$XUI_PANEL_PORT" "$XUI_WEB_BASE_PATH" '
            '"$XUI_ACCESS_URL" "$XUI_API_TOKEN" "$XUI_DB_TYPE"'
        )
        result = await self.executor.run(spec, command, timeout_seconds=20.0)
        if result.exit_status != 0:
            raise RuntimeError("3X-UI configuration extraction failed")
        values = result.stdout.split("\0")
        if values and values[-1] == "":
            values.pop()
        if len(values) != 7:
            raise RuntimeError("3X-UI configuration result is incomplete")
        username, password, port, base_path, access_url, api_token, db_type = values
        try:
            panel_port = int(port)
        except ValueError as exc:
            raise RuntimeError("3X-UI panel port is invalid") from exc
        if not all((username, password, base_path, access_url, api_token, db_type)):
            raise RuntimeError("3X-UI configuration result contains blank required fields")
        return ThreeXUiConfig(
            username=username,
            password=SecretStr(password),
            panel_port=panel_port,
            web_base_path=base_path,
            access_url=access_url.rstrip("/"),
            api_token=SecretStr(api_token),
            db_type=db_type,
        )

    async def rollback(self, spec: SshConnectionSpec) -> None:
        # Rollback is deliberately non-destructive: stop a partial service and remove only our
        # temporary installer. The replacement VPS itself remains available for provider cleanup or
        # post-mortem; this component can never touch the old VPS.
        await self.executor.run(
            spec,
            "rm -f /tmp/aso-3xui-install.sh; "
            "systemctl stop x-ui >/dev/null 2>&1 || rc-service x-ui stop >/dev/null 2>&1 || true",
            timeout_seconds=20.0,
        )
